# Usa la imagen base de GCC
FROM gcc:latest

# Instala cualquier dependencia adicional que necesites (opcional)
# RUN apt-get update && apt-get install -y <paquete>

# Establece el directorio de trabajo
WORKDIR /workspace

# Copia todo el código del proyecto dentro del contenedor
COPY . /workspace
